### ISSUE TITLE
The dimension problem of the first convolutional layer

### ISSUE THREAD

**Issue by cjh-yan** [wngh1187/ExU-Net#4]
Hi,

Thank you for making the code & pretrained models public.When I was debuggy, I found that the input dimension of the first convolutional layer seemed different from that in the paper.
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/126657299/227141859-46f6ccf7-4fcc-48f6-ba60-a41f4f721988.png">

**Comment by wngh1187** [comment]
Thank you for your interest in our research and for bringing us to your attention. As you pointed out, I have confirmed that there is an error in the Figure 2.
Our system takes as input a 64-dimensional mel spectrogram rather than a 32-dimensional one. This means that we actually used a 64-dimensional spectrogram in our implementation, which can be seen in the first line of section "4.2 Implementation Details".
We apologize for any confusion this error may have caused and will include a corrected picture in the README. 
Thanks again for your valuable comments.
